import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

export default function HomePage() {
  let arr = [];
  for(let i =6;i>0;i--){
    arr.push(<img src={`/${i}.jpg`} alt="" key={i}/>)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Lets create wavesolution website.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.jpg" />
      </Head>
      <main>
        <header>
          <br />
          <h1>Wavesolution</h1>
          <p><Link href='/web'>Web</Link> <br /> <a href="ui-ux">UI/UX</a> </p>
        
        <br /><br />

        {arr}
        
        </header>
      </main>

    </div>
  )
}
